spring.application.name=shelf-service
server.port=${SERVER_PORT:8085}

spring.data.mongodb.uri=mongodb://${MONGO_USER:admin}:${MONGO_PASSWORD:admin}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/playbook_db?authSource=admin