spring.application.name=user-service
server.port=${SERVER_PORT:8081}

spring.data.mongodb.uri=mongodb://${MONGO_USER:admin}:${MONGO_PASSWORD:admin}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/playbook_db?authSource=admin

jwt.secret=${JWT_SECRET:4a5z9j78sdf08f7h9g0k34d23n9dbjsdlfjf39g94hds92hf3}
jwt.lifetime=${JWT_LIFETIME:3600000}
